// Generated by CoffeeScript 1.6.1
var Registry;

Registry = (function() {

  Registry.prototype.variables = null;

  /*
  Constructs an instance of Registry. Called when simple-registry
  is first required.
  */


  function Registry() {
    this.variables = {};
  }

  /*
  Associates a value with a key. The key should be a string
  @param string key
  @param object value
  */


  Registry.prototype.set = function(key, value) {
    return this.variables[key] = value;
  };

  /*
  Returns the value previously associated with the given key.
  @param string key
  */


  Registry.prototype.get = function(key) {
    return this.variables[key];
  };

  /*
  Returns true if the given key has been associated with
  a value.
  @param string key
  */


  Registry.prototype.has = function(key) {
    return key in this.variables;
  };

  /*
  Removes any value associated with the given key.
  @param string key
  */


  Registry.prototype.remove = function(key) {
    if (this.has(key)) {
      return delete this.variables[key];
    }
  };

  return Registry;

})();

module.exports = new Registry();
